config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	root 'books#home'
	get 'home/about' => 'books#about', as: 'about_book'
	post 'favorites/:id' => 'favorites#create', as: 'favorite'
	delete 'favorites/:id' => 'favorites#destroy', as: 'favorites'
	post 'comments' => 'book_comments#create', as: 'comment'
	delete 'comments/:id' => 'book_comments#destroy', as: 'comments'
  get 'search' => 'searches#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  resources :relationships, only: [:create, :destroy]
  resources :users, only: [:show, :edit, :update, :index] do
  	member do
  		get :following, :followers
  	end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy

	validates :title, :body, presence: true
	validates :body, length: {maximum:200}

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	def favorites_count
		favorites.count.to_s
	end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :book
	belongs_to :user

	validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates_uniqueness_of :book_id, scope: :user_id

end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name:"User"
	belongs_to :followed, class_name:"User"
	validates :followed_id, presence: true
	validates :follower_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", 
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  attachment :profile_image

  validates :name, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}


  def follow(user)
    following << user
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    following.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	before_action :authenticate_user!, except: [:home, :about]



	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
		devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
	end

	def after_sign_in_path_for(resource)
		user_path(resource)
	end

	def after_sign_up_path_for(resource)
		user_path(resource)
	end


end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

	def create
		@comment = current_user.book_comments.new(comment_params)
		@book = Book.find(@comment.book_id)
		if @comment.save
			flash[:notice] = "successfully upload comment!"
			redirect_to @book
		else
			@book_new = Book.new
			@user = @book.user
			@comments = BookComment.all
			render "books/show"
		end
	end

	def destroy
		@comment = BookComment.find(params[:id])
		book = Book.find(@comment.book_id)
		if @comment.user == current_user
			@comment.destroy
			flash[:notice] = "successfully deleted!"
		else
			flash[:notice] = "You cannot delete this comment"
		end
		redirect_to book
	end

	private

	def comment_params
		params.require(:book_comment).permit(:content, :book_id)
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	before_action :set_book, only: [:show, :edit, :update, :destroy]

	def home
	end
	
	def about
	end

	def index
		@books = Book.all
		@book = Book.new
	end

	def show
		@book_new = Book.new
		@user = @book.user
		@comment = BookComment.new
		@comments = BookComment.all
	end

	def create
		@book = current_user.books.new(book_params)
		if @book.save
			flash[:notice] = "Book was successfully created."
			redirect_to @book
		else
			@books = Book.all
			render :index
		end
	end

	def edit
		redirect_to books_url if @book.user != current_user
	end


	def update
		if @book.update(book_params)
			flash[:notice] = "Book was successfully updated."
			redirect_to @book
		else
			render :edit
		end
	end

	def destroy
		@book.destroy
		redirect_to books_path
	end

	private

		def set_book
			@book = Book.find(params[:id])
		end

		def book_params
			params.require(:book).permit(:title, :body)
		end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	before_action :set_book

	def create
		#binding.pry
		Favorite.new(book_id: @book.id,
			         user_id: current_user.id).save unless @book.favorited_by?(current_user)
		redirect_back(fallback_location: books_path)
	end

	def destroy
		#binding.pry
		Favorite.find_by(user_id: current_user.id, book_id: @book.id).destroy if @book.favorited_by?(current_user)
		redirect_back(fallback_location: books_path)
	end

	private

	  def set_book
	  	@book = Book.find(params[:id])
	  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

	def create
		@user = User.find(params[:followed_id])
		current_user.follow(@user) unless current_user.following?(@user)
		redirect_back(fallback_location: @user)
	end

	def destroy
		@user = Relationship.find(params[:id]).followed
		current_user.unfollow(@user)
		redirect_back(fallback_location: @user)
	end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
	include ApplicationHelper

	def search
		@book = Book.new
		if params[:search][:target] == "book"
			@books = Book.where(['title LIKE ?', search_by(params[:search][:key],
														params[:search][:way])])
			render 'books/index' and return
		elsif params[:search][:target] == "user"
			@users = User.where(['name LIKE ?', search_by(params[:search][:key],
															params[:search][:way])])
			render 'users/index' and return
		end
		flash[:notice] = "Select what you want to search"
		redirect_to current_user
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :following, :followers]

  def show
  	@book = Book.new
  	@books = @user.books.all
  end

  def index
  	@users = User.all
  	@book = Book.new
  end

  def following
    @title = "Following"
    @users = @user.following.all
    render 'follow_index'
  end

  def followers
    @title = "Followers"
    @users = @user.followers.all
    render 'follow_index'
  end

  def edit
      redirect_to current_user unless @user == current_user
  end

  def update
  	if @user.update(user_params)
      flash[:notice] = "successfully updated."
      redirect_to @user
    else
      render :edit
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
    	params.require(:user).permit(:name, :introduction, :profile_image)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def search_by(key, way)
		case way.to_i
		when 1
			"#{key}"
		when 2
			"#{key}%"
		when 3
			"%#{key}"
		when 4
			"%#{key}%"
		else
			flash[:notice] = "Select the way you search the object"
			return
		end
	end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_comment_form.html.erb
<!-- recieves book comment -->

<td colspan="2">
	<%= form_for(comment, url: comment_path(book)) do |f| %>
	 <%= hidden_field_tag :book_id, book.id %>
	 <%= f.text_area :content, placeholder: "Comment here...", class:"col-xs-10" %>
	 <%= f.submit "送信" %>
	<% end %>
</td>

app/views/books/_comments.html.erb
<!-- recieves book comments -->
<tbody><% comments.each do |comment| %>
	<tr><td>
		<%= comment.content %>
		</td>
		<% if comment.user_id == current_user.id %>
		<td><%= link_to "Delete", comments_path(comment), method: :delete, "data-confirm" => "本当に消しますか？", class:"btn btn-danger" %></td>
		<% end %>
	</tr>
	<% end %>
</tbody>

app/views/books/_edit_destroy_buttons.html.erb
<!-- recieves book -->

<% if book.user == current_user %>
<td class="text-right"><%= link_to "Edit", edit_book_path(book), class:"btn btn-success" %></td>
<td class="text-right"><%= link_to "Destroy", book_path(book), method: :delete, "data-confirm" => "本当に消しますか？", class:"btn btn-danger" %></td>
<% end %>

app/views/books/_favorite.html.erb
<!-- recieves book -->
<td>
<% if book.favorited_by?(current_user) %>
  <%= link_to favorites_path(book), method: :delete do %>
    <i class="fas fa-heart"></i>
  <% end %>
<% else %>
  <%= link_to favorite_path(book), method: :post do %>
    <i class="far fa-heart"></i>
  <% end %>
<% end %>
<%= book.favorites_count %>
</td>

app/views/books/about.html.erb
<h1>Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers</strong>!</h1>

app/views/books/edit.html.erb

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1>Editing Book</h1>

		<%= render 'devise/shared/error_messages', resource: @book %>

		<%= form_for(@book) do |f| %>


		<%= f.label :title, "Title" %><br>
		<%= f.text_field :title, class:"col-xs-12" %>

		<%= f.label :body, "Opinion" %><br>
		<%= f.text_area :body, class:"col-xs-12"%>

		<div class ="create-btn">
			<%= f.submit 'Update Book', class:"btn btn-primary col-xs-12" %>
		</div>
		
		<% end %>
		<%= link_to "Show", @book %><span> | </span>
		<%= link_to "Back", books_path %>
	</div>
</div>


app/views/books/home.html.erb
<div class="row">
	<div class="top-message col-md-offset-3 col-md-6">
		<h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers</strong> !!</h1>
		<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers</strong>,</p>
		<p>you can share and exchange your opinions, inpressions, and emotions about various books!</p>
		<div class="btn-wrapper">
			<div class="row">
				<%= link_to "Log In", new_user_session_path, class:'btn btn-info col-xs-10 col-xs-offset-1 sign_in' %>
			</div>
			<div class="row">
				<%= link_to "Sign Up", new_user_registration_path, class:'btn btn-success col-xs-10 col-xs-offset-1 sign_up' %>
			</div>
		</div>
	</div>
</div>

app/views/books/index.html.erb
<%= render 'devise/shared/error_messages', resource: @book %>
<%= render 'layouts/template', book: @book, user: current_user, books: @books %>

app/views/books/show.html.erb

<div class="row">
	<%= render 'layouts/sidebar', book: @book_new, user: @user %>
	<div class="col-xs-9">
		<h2>Book detail</h2>
		<table class="table">
			<tr>
				<td style="font-weight: 20;"><%= link_to @book.user do %><%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpg', fallback: "noimages.png", size:'50x50' %><br><%= @book.user.name %><% end %></td>
				<td style="font-weight: 20;"><%= link_to @book.title, @book %></td>
				<td style="font-weight: 20;"><%= @book.body %></td>
				<%= render 'books/favorite', book: @book %>
				<td><%= pluralize(@book.book_comments.count, 'comment') %></td>
				<%= render 'books/edit_destroy_buttons', book: @book %>
			</tr>
		</table>
		<table class="table">
			<h3>Comments</h3>
			<%= render 'books/comments', comments: @comments, book: @book %>
			<tr border="none"><td><%= render 'devise/shared/error_messages', resource: @comment %></td></tr>
			<tr border="none"><%= render 'books/comment_form', book: @book, comment: @comment %></tr>
		</table>
	</div>
</div>

app/views/layouts/_book_form.html.erb
<%= form_for(book) do |f| %>
	<%= f.label :title, "Title" %><br>
	<%= f.text_field :title , class:"col-xs-12"%>
	<%= f.label :body, "Opinion" %>
	<%= f.text_area :body , class:"col-xs-12"%>
	<div class ="create-btn">
		<%= f.submit 'Create Book', class:"btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/layouts/_profile.html.erb
<!-- recieves user -->

<%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpg', fallback: "noimages.png", size:'100x100' %>
	<table class="table">
		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>
		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
		<tr>
			<th>follows</th>
			<th><%= link_to user.following.count, following_user_path(user) %></th>
		</tr>
		<tr>
			<th>followers</th>
			<th><%= link_to user.followers.count, followers_user_path(user) %></th>
		</tr>
	</table>

app/views/layouts/_search_form.html.erb
<!-- recieve -->

<% if user_signed_in? %>
<%= form_with(scope: :search, url: search_path, method: :get, local: true) do |f| %>

      <%= f.text_field :key %>

      <%= f.select :target, [["User", "user"],["Book", "book"]] %>

      <%= f.select :way, [["完全一致", 1],["前方一致", 2],
      						["後方一致", 3],["部分一致", 4]] %>

      <%= f.submit 'Search' %>

<% end %>
<% end %>

app/views/layouts/_sidebar.html.erb
<!-- recieves user book -->
<div class="col-xs-3">
	<h2>User info</h2>
	<%= render 'layouts/profile', user: user %>

	<%= render 'users/follow_button', user: user %>

	<%= link_to((user == current_user)? edit_user_path(user):current_user, class:"col-xs-12 btn btn-default submit-btn", id:"btnn", style:"height: 35px;") do %><span class="glyphicon glyphicon-wrench"></span><% end %>

	<div class="row">
		<h2>New book</h2>
		<%= render 'layouts/book_form', book: book %>
	</div>
</div>

app/views/layouts/_template.html.erb

	<div class="row">
		<%= render 'layouts/sidebar', book: book, user: user %>
		<div class="col-xs-9">
			
			<h2>Books</h2>
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
					</tr>
				</thead>
				<% books.each do |book| %>
				<tbody>
					<tr>
						<td><%= link_to user_path(book.user) do %><%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: 'jpg', fallback: "noimages.png", size:'50x50' %><% end %></td>
						<td><%= link_to book.title, book_path(book) %></td>
						<td><%= book.body %></td>
						<td><%= pluralize(book.book_comments.count, 'comment') %></td>
						<td><%= render 'books/favorite', book: book %></td>
					</tr>
				</tbody>
				<% end %>
			</table>
		</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookers</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://kit.fontawesome.com/df5d430224.js" crossorigin="anonymous"></script>
</head>

<body>

  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <h4>Bookers</h4>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to current_user do %><span class="glyphicon glyphicon-home" aria-hidden="true"></span>　Home<% end %></li>
              <li><%= link_to(users_path) do %><span class="glyphicon glyphicon-user" aria-hidden="true"></span>　Users<% end %></li>
              <li><%= link_to(books_path) do %><span class="glyphicon glyphicon-book" aria-hidden="true"></span>　Books<% end %></li>
              <li><%= link_to(destroy_user_session_path, method: :delete) do %><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>　logout<% end %></li>
            <% else %>
              <li><%= link_to root_path do %><span class="glyphicon glyphicon-home" aria-hidden="true"></span>　Home<% end %></li>
              <li><%= link_to(about_book_path) do %><span class="glyphicon glyphicon-link" aria-hidden="true"></span>　About<% end %></li>
              <li><%= link_to(new_user_registration_path) do %><span class="glyphicon glyphicon-edit" aria-hidden="true"></span>　sign up<% end %></li>
              <li><%= link_to(new_user_session_path) do %><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>　login<% end %></li>
            <% end %>
          </ul>
        </nav>
    </div>
  </header>

<div class="container body">

  <div class="search_form text-center">
    <%= render 'layouts/search_form' %>
  </div>

  <div class="flash">
    <% if flash[:notice] %><%= flash[:notice] %><% end %>
  </div>
  
  <%= yield %>

</div>

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-xs-3 col-xs-offset-9">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
  <%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/users/_follow.html.erb
<!-- recieves user -->

<%= form_for(current_user.active_relationships.new) do |f| %>
	<%= hidden_field_tag :followed_id, user.id %>
	<%= f.submit "Follow", class:"btn btn-success col-xs-12" %>
<% end %>

app/views/users/_follow_button.html.erb
<!-- recieves user -->

<% if user != current_user %>
	<% if current_user.following?(user) %>
		<%= render 'users/unfollow', user: user %>
	<% else %>
		<%= render 'users/follow', user: user %>
	<% end %>
<% end %>


app/views/users/_follow_link.html.erb
<!-- recieves user -->

<% if user != current_user %>
	<%= current_user.following?(user)?
	button_to("Unfollow", relationship_path(current_user.active_relationships.find_by(followed_id: user.id)), method: :delete):
	button_to("Follow", relationships_path, params:{followed_id: user.id}, method: :post) %>
<% end %>

app/views/users/_unfollow.html.erb
<!-- recieve user -->

<%= form_for(current_user.active_relationships.find_by(followed_id: user.id),
                                             html:{method: :delete}) do |f| %>
	<%= f.submit "Unfollow", class:"btn btn-primary col-xs-12" %>
<% end %>

app/views/users/_users.html.erb
<!-- recieves users -->

<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
		</tr>
	</thead>
	<% users.each do |user| %>
	<tbody>
		<tr>
			<td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpg', fallback: "noimages.png", size:'50x50' %></td>
			<td><%= user.name %></td>
			<td><%= pluralize(user.following.count, 'following')%></td>
			<td><%= pluralize(user.followers.count, 'follower')%></td>
			<td><%= render 'users/follow_link', user: user %></td>
			<td><%= link_to "Show", user %></td>
		</tr>
	</tbody>
	<% end %>
</table>

app/views/users/edit.html.erb
	<h1>User info</h1>
	<%= render 'devise/shared/error_messages', resource: @user %>
	<%= form_for(@user) do |f| %>
	<div>
		<%= f.label :name, "Name" %>
		<%= f.text_field :name %>
	</div>
	<div>
		<%= f.label :profile_image, "Image" %>
		<%= f.attachment_field :profile_image %>
	</div>
	<div>
		<%= f.label :introduction, "Introduction" %>
		<%= f.text_area :introduction %>
	</div>
	<div>
		<%= f.submit 'Update User' %>
	</div>

	<% end %>

app/views/users/follow_index.html.erb
<h2><%= "User #{@title}" %></h2>
<%= render 'users/users', users: @users %>

app/views/users/index.html.erb
<div class="row">
	<%= render 'layouts/sidebar', book: @book, user: current_user %> 
	<div class="col-xs-9">
		<h2>Users</h2>
		<%= render 'users/users', users: @users %>
	</div>
</div>

app/views/users/show.html.erb
<%= render 'layouts/template', book: @book, user: @user, books: @books %>